# Generated by Django 3.2.6 on 2021-08-16 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_job_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company_country',
            new_name='job_post',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_place',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_zipcode',
        ),
    ]
