# Generated by Django 3.2.6 on 2021-08-16 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210816_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='content',
            new_name='notes',
        ),
    ]
